site_name: English Studies
site_url: https://example.com/
nav:
  - Home: index.md
  - book 7:
    - Lesson 1: book-7/lesson-01.md
    - Lesson 2: book-7/lesson-02.md
    - Lesson 3: book-7/lesson-03.md
    - Lesson 4: book-7/lesson-04.md
    - Lesson 5: book-7/lesson-05.md
    - Lesson 6: book-7/lesson-06.md
    - Lesson 7: book-7/lesson-07.md
    - Lesson 8: book-7/lesson-08.md
    - Lesson 9: book-7/lesson-09.md
    - Lesson 10: book-7/lesson-10.md

  - book 8:
    - Lesson 1: book-8/lesson-01.md
    - Lesson 2: book-8/lesson-02.md
    - Lesson 3: book-8/lesson-03.md
    - Lesson 4: book-8/lesson-04.md
    - Lesson 5: book-8/lesson-05.md
    - Lesson 6: book-8/lesson-06.md
    - Lesson 7: book-7/lesson-07.md
    - Lesson 8: book-8/lesson-08.md
    - Lesson 9: book-9/lesson-09.md
theme: readthedocs