site_name: English
site_url: https://example.com/
nav:
  - Home: index.md
  - book 7:
    - Chapter 1: book-7/chapter-01.md
    - Chapter 2: book-7/chapter-02.md
    - Chapter 3: book-7/chapter-03.md
    - Chapter 4: book-7/chapter-04.md
    - Chapter 5: book-7/chapter-05.md
    - Chapter 6: book-7/hapter-06.md
    - Chapter 7: book-7/chapter-07.md
    - Chapter 8: book-7/chapter-08.md
    - Chapter 9: book-7/chapter-09.md
    - Chapter 10: book-7/chapter-10.md

